sudo: false
language: node_js
node_js:
  - 15 # use nodejs v15 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - sed -i '1,$s/](\.\.\/img/](\/img/g' source/_posts/*.md
  - hexo cl
  - hexo generate # generate static files
  - hexo d
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
  target: gh-pages